from . import test_analysis
from . import test_mapping

from . import test_security
from . import test_course_selection
from . import test_course_profile
from . import test_course_profile_safety
from . import test_course_mapping
from . import test_course_mapping_engine
from . import test_course_mapping_prerequisite
from . import test_course_mapping_policy
from . import test_course_mapping_visibility
from . import test_course_mapping_ui
from . import test_curriculum_reference
from . import test_curriculum_bootstrap
from . import test_curriculum_public_units
from . import test_curriculum_coverage
from . import test_curriculum_module
from . import test_curriculum_gap_analysis
from . import test_curriculum_candidate_selection
from . import test_curriculum_ui
from . import test_curriculum_lesti_case
from . import test_curriculum_release_invariants
from . import test_curriculum_source_lifecycle
from . import test_discovery_run
from . import test_course_discovery
from . import test_youtube_service
