{
    "name": "FACODI Learning",
    "summary": "Standard-first analysis and educational mapping for Odoo eLearning",
    "version": "19.0.1.9.0",
    "category": "Website/eLearning",
    "author": "FACODI",
    "website": "https://facodi.com",
    "license": "LGPL-3",
    "depends": ["website_slides"],
    "data": [
        "security/ir.model.access.csv",
        "security/facodi_learning_security.xml",
        "data/ir_cron.xml",
        "views/slide_slide_views.xml",
        "views/analysis_views.xml",
        "views/course_candidate_views.xml",
        "views/course_candidate_discovery_views.xml",
        "views/discovery_run_views.xml",
        "views/course_mapping_views.xml",
        "views/curriculum_views.xml",
        "views/curriculum_module_views.xml",
        "views/website_curriculum.xml",
        "views/source_views.xml",
        "views/website_slides.xml",
        "views/res_config_settings_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
