{
    "name": "FACODI Learning",
    "summary": "Standard-first analysis and educational mapping for Odoo eLearning",
    "version": "19.0.1.42.0",
    "category": "Website/eLearning",
    "author": "FACODI",
    "website": "https://facodi.com",
    "license": "LGPL-3",
    "depends": ["portal", "website_slides"],
    "data": [
        "security/ir.model.access.csv",
        "security/facodi_learning_security.xml",
        "data/ir_cron.xml",
        "data/website_menu.xml",
        "views/slide_slide_views.xml",
        "views/analysis_views.xml",
        "views/submission_views.xml",
        "views/submission_context_views.xml",
        "views/submission_candidate_handoff_views.xml",
        "views/course_candidate_views.xml",
        "views/course_candidate_discovery_views.xml",
        "views/discovery_run_views.xml",
        "views/course_mapping_views.xml",
        "views/curriculum_views.xml",
        "views/curriculum_module_views.xml",
        "views/website_curriculum.xml",
        "views/website_explore.xml",
        "views/website_submission.xml",
        "views/portal_home.xml",
        "views/source_views.xml",
        "views/content_review_views.xml",
        "views/website_slides.xml",
        "views/res_config_settings_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "assets": {
        "web.assets_frontend": [
            "facodi_learning/static/src/js/resource_submission.js",
        ],
    },
    "installable": True,
    "application": False,
}
